#!/usr/bin/env python3

import requests
try:
    r = requests.get('https://api.coinmarketcap.com/v1/ticker/iota/?convert=EUR');

    ticker = r.json()
    print('%.2f' % float(ticker[0]['price_eur']))
except requests.ConnectionError:
    print("---")
